# Generated by Django 4.2.8 on 2024-01-09 13:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Text',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('text', models.TextField(verbose_name='Текст')),
            ],
            options={
                'verbose_name': 'Глобальный текст',
                'verbose_name_plural': 'Глобальный текст',
            },
        ),
        migrations.CreateModel(
            name='Workers',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('surname', models.CharField(max_length=20, verbose_name='Фамилия')),
                ('name', models.CharField(max_length=20, verbose_name='Имя')),
                ('patronymic', models.CharField(max_length=20, verbose_name='Отчество')),
                ('birthdate', models.DateField(verbose_name='Дата рождения')),
                ('text', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workers', to='homepage.text', verbose_name='Текст')),
            ],
            options={
                'verbose_name': 'Работник',
                'verbose_name_plural': 'Работники',
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=50, verbose_name='Название')),
                ('anons', models.CharField(max_length=250, verbose_name='Анонс')),
                ('date', models.DateTimeField(verbose_name='Дата публикации')),
                ('text', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='news', to='homepage.text', verbose_name='Текст')),
            ],
            options={
                'verbose_name': 'Новость',
                'verbose_name_plural': 'Новости',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Appeal',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=50, verbose_name='Название')),
                ('text', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appeal', to='homepage.text', verbose_name='Текст')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL, verbose_name='Индефикатор пользователя')),
            ],
            options={
                'verbose_name': 'Обращения граждан',
                'verbose_name_plural': 'Обращения граждан',
            },
        ),
        migrations.CreateModel(
            name='Aktirovka',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=50, verbose_name='Название')),
                ('date', models.DateTimeField(verbose_name='Дата публикации')),
                ('text', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aktirovka', to='homepage.text', verbose_name='Текст')),
            ],
            options={
                'verbose_name': 'Актировка',
                'verbose_name_plural': 'Актировки',
                'ordering': ['-date'],
            },
        ),
    ]
